-- upgrade --
ALTER TABLE "clinic" ALTER COLUMN "lang" TYPE VARCHAR(500) USING "lang"::VARCHAR(500);
ALTER TABLE "clinic" ALTER COLUMN "lat" TYPE VARCHAR(500) USING "lat"::VARCHAR(500);
-- downgrade --
ALTER TABLE "clinic" ALTER COLUMN "lang" TYPE VARCHAR(200) USING "lang"::VARCHAR(200);
ALTER TABLE "clinic" ALTER COLUMN "lat" TYPE VARCHAR(200) USING "lat"::VARCHAR(200);
